apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mul-chatbot
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        # Scale to zero when idle (cost saving)
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        # CPU only allocated during request processing
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 120
      containers:
        - image: gcr.io/mul-agent-with-langgraph/mul-chatbot
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: ENV
              value: "production"
            - name: LANGCHAIN_TRACING_V2
              value: "true"
            - name: LANGCHAIN_PROJECT
              value: "mul-chatbot"
            # API keys injected from GCP Secret Manager (never hardcoded)
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_API_KEY
                  key: latest
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: TAVILY_API_KEY
                  key: latest
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: LANGCHAIN_API_KEY
                  key: latest
